name: PR Changelogs
concurrency: commit_action
on:
  pull_request_target:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHANGELOG_DIR: Resources/Changelog/Wayfarer.yml # Frontier: Changelog.yml<Wayfarer.yml
  PR_NUMBER: ${{ github.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER || 'Wayfarer Bot' }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL || 'noreply@github.com' }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/_NF/changelog"
          npm install
        shell: bash

      - name: Generate Changelog
        run: |
          cd "Tools/_NF/changelog"
          node changelog.js
        shell: bash

      - name: Commit Changelog
        run: |
          git pull origin master
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE || 'Update Changelog' }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        continue-on-error: true
